// <auto-generated />
using JWTAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JWTAPI.Migrations
{
    [DbContext(typeof(JWTDbContext))]
    [Migration("20201011085406_InitialDbCreation")]
    partial class InitialDbCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JWTAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vel dolores et accumsan te",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "No diam tincidunt duo nonumy",
                            Price = 2300.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lorem rebum amet dolor",
                            Price = 4300.0
                        });
                });

            modelBuilder.Entity("JWTAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Marshal",
                            Password = "john1234",
                            UserName = "john"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Allen",
                            LastName = "Green",
                            Password = "allen1234",
                            UserName = "allen"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Smith",
                            LastName = "Wood",
                            Password = "smith1234",
                            UserName = "smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
